### ISSUE TITLE
Memory leak on loading mat file

### ISSUE THREAD

**Issue by ArthurTu** [soumith/matio-ffi.torch#1]
I am sure there is memory leak after loading mat files. After loading lots of '.mat' files, the memory is occupied.

I tried to add 'mat.varFree()' before 'mat.close()'. But it didn't seem to help.

**Comment by jonathanasdf** [comment]
Reviving this thread.

This is now happening to me on Ubuntu 16.04 with various versions of libmatio (have tried 1.5.8, 1.5.6 and 1.5.2), even with a collectgarbage() call:

```
local mat = require 'matio'
for i=1,1000000000 do
   collectgarbage()
   local a=mat.load('test.mat')
end
```

Here is a mat file: https://dl.dropboxusercontent.com/u/4910378/test.mat

**Comment by SelvamArul** [comment]
@jonathanasdf  I am facing the same issue. Any workarounds for this?

**Comment by jonathanasdf** [comment]
For my case I just converted the mat file to a t7 file and proceeded with loading the t7 file instead.

**Comment by SelvamArul** [comment]
@jonathanasdf  Thanks a lot for your suggestion. It will try this.

**Comment by ranhan429** [comment]
also leaking on my system. garbage collection won't help. Can anyone help solve this?

BTW - how did you convert mat files to t7?

**Comment by hangong** [comment]
There is a bug of memory leak.

The code below will give you the leak
```
mat = require 'matio'
for i=1,1000000000 do
   a = mat.load('test.mat')
   b = a['a'];
end
```

However, if you modify it to
```
mat = require 'matio'
for i=1,1000000000 do
   a = mat.load('test.mat', 'a')
   b = a['a'];
end
```
Then, there is no leak.

Maybe you can reopen the issue? Tested on Ubuntu 16.04.
