### ISSUE TITLE
Matio won't load .mat files

### ISSUE THREAD

**Issue by lakehanne** [soumith/matio-ffi.torch#19]
Hey,

My matio was installed from the ubuntu repo and I did follow up with `luarocks install matio` but it seems the devils are really unhappy with me:

>th> tensor = matio:load('vicon.mat', 'vicon')
[string "tensor = matio:load('vicon.mat', 'vicon')"]:1: attempt to index global 'matio' (a nil value)
stack traceback:
	[string "tensor = matio:load('vicon.mat', 'vicon')"]:1: in main chunk
	[C]: in function 'xpcall'
	/home/lex/torch/install/share/lua/5.1/trepl/init.lua:668: in function 'repl'
	.../lex/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:199: in main chunk
	[C]: at 0x00406670	
                 
Matlab versioon is 8.6.0.267246 (R2015b).

Any ideas?

**Comment by soumith** [comment]
did you try a 

    th> require 'matio'

first

**Comment by lakehanne** [comment]
Yes indeed.

>require 'matio'
{
  load : function: 0x40363560
  use_lua_strings : false
  save : function: 0x40363650
  __make_var : function: 0x40363368
  compression : 1
  ffi : 
    {
      varPrint : cdata<void ()>: 0x7f94c23a1410
      FT_MAT73 : 512
      T_INT64 : 12
      F_DONT_COPY_DATA : 1
      T_INT32 : 5
      BY_INDEX : 2
      T_UNKNOWN : 0
      F_GLOBAL : 1024
      BY_NAME : 1
      C_UINT16 : 11
      logInitFunc : cdata<int ()>: 0x7f94c237e790
      C_INT16 : 10
      setVerbose : cdata<int ()>: 0x7f94c237e370
      T_UINT64 : 13
      C_INT8 : 8
      T_DOUBLE : 9
      open : cdata<struct _mat_t *()>: 0x7f94c23a0800
      getLibraryVersion : cdata<void ()>: 0x7f94c239fe10
      varGetStructs : cdata<struct matvar_t *()>: 0x7f94c23a2d90
      varDuplicate : cdata<struct matvar_t *()>: 0x7f94c23a00a0
      T_UTF8 : 16
      close : cdata<int ()>: 0x7f94c239fe70
      C_FUNCTION : 16
      varReadData : cdata<int ()>: 0x7f94c23a1d10
      C_UINT64 : 15
      varGetSize : cdata<uint64_t ()>: 0x7f94c23a1300
      debugMessage : cdata<int ()>: 0x7f94c237e450
      calcSingleSubscript : cdata<int ()>: 0x7f94c23a1170
      varGetCell : cdata<struct matvar_t *()>: 0x7f94c23a2470
      varWriteData : cdata<int ()>: 0x7f94c23a20a0
      varWriteInfo : cdata<int ()>: 0x7f94c23a2070
      C_OBJECT : 3
      varWrite : cdata<int ()>: 0x7f94c23a2230
      T_SINGLE : 7
      T_STRING : 20
      varSetStructFieldByIndex : cdata<struct matvar_t *()>: 0x7f94c23a3310
      logClose : cdata<int ()>: 0x7f94c237e740
      varSetCell : cdata<struct matvar_t *()>: 0x7f94c23a27b0
      ACC_RDWR : 1
      sizeOfClass : cdata<uint64_t ()>: 0x7f94c239ffa0
      varReadNextInfo : cdata<struct matvar_t *()>: 0x7f94c23a1de0
      C_CELL : 1
      varReadNext : cdata<struct matvar_t *()>: 0x7f94c23a1ff0
      varGetStructFieldByName : cdata<struct matvar_t *()>: 0x7f94c23a2c20
      critical : cdata<void ()>: 0x7f94c237e5d0
      varSetStructFieldByName : cdata<struct matvar_t *()>: 0x7f94c23a33f0
      varGetStructsLinear : cdata<struct matvar_t *()>: 0x7f94c23a3160
      FT_MAT4 : 16
      T_MATRIX : 14
      varReadDataAll : cdata<int ()>: 0x7f94c23a1d60
      COMPRESSION_NONE : 0
      varGetStructField : cdata<struct matvar_t *()>: 0x7f94c23a2d10
      varReadInfo : cdata<struct matvar_t *()>: 0x7f94c23a1e20
      error : cdata<void ()>: 0x7f94c237e670
      C : userdata: 0x400ff268
      createVer : cdata<struct _mat_t *()>: 0x7f94c239fe40
      T_UTF32 : 18
      varGetStructFieldnames : cdata<char *const *()>: 0x7f94c23a2b30
      verbMessage : cdata<int ()>: 0x7f94c237e510
      setDebug : cdata<int ()>: 0x7f94c237e380
      T_ARRAY : 23
      varAddStructField : cdata<int ()>: 0x7f94c23a29c0
      varGetNumberOfFields : cdata<unsigned int ()>: 0x7f94c23a2b10
      calcSubscripts : cdata<int *()>: 0x7f94c23a1220
      varGetCellsLinear : cdata<struct matvar_t **()>: 0x7f94c23a2740
      T_FUNCTION : 24
      varGetCells : cdata<struct matvar_t **()>: 0x7f94c23a24d0
      varFree : cdata<void ()>: 0x7f94c23a0470
      varDelete : cdata<int ()>: 0x7f94c23a2280
      C_UINT32 : 13
      varCreateStruct : cdata<struct matvar_t *()>: 0x7f94c23a2810
      T_UINT32 : 6
      C_UINT8 : 9
      FT_MAT5 : 256
      C_DOUBLE : 6
      T_COMPRESSED : 15
      varCreate : cdata<struct matvar_t *()>: 0x7f94c23a0bb0
      C_CHAR : 4
      C_INT32 : 12
      T_INT8 : 1
      C_EMPTY : 0
      T_STRUCT : 22
      rewind : cdata<int ()>: 0x7f94c239ff30
      getVersion : cdata<enum mat_ft ()>: 0x7f94c239ff10
      T_UINT16 : 4
      C_STRUCT : 2
      getFilename : cdata<const char *()>: 0x7f94c239fef0
      varGetStructFieldByIndex : cdata<struct matvar_t *()>: 0x7f94c23a2b60
      T_UTF16 : 17
      sizeOf : cdata<uint64_t ()>: 0x7f94c237e860
      warning : cdata<void ()>: 0x7f94c237e7c0
      varCalloc : cdata<struct matvar_t *()>: 0x7f94c239ffc0
      T_CELL : 21
      varRead : cdata<struct matvar_t *()>: 0x7f94c23a1f60
      ACC_RDONLY : 0
      varReadDataLinear : cdata<int ()>: 0x7f94c23a1d90
      C_SPARSE : 5
      F_LOGICAL : 512
      T_UINT8 : 2
      message : cdata<int ()>: 0x7f94c237e390
      C_SINGLE : 7
      C_INT64 : 14
      F_COMPLEX : 2048
      COMPRESSION_ZLIB : 1
      T_INT16 : 3
      help : cdata<void ()>: 0x7f94c237e710
      logInit : cdata<int ()>: 0x7f94c237e760
    }
}

**Comment by soumith** [comment]
sorry, the line should be:

    th> matio = require 'matio'

**Comment by lakehanne** [comment]
Yes I know. It was kind of omitted. You don't sleep? :)

**Comment by soumith** [comment]
yea,
matio = require 'matio'
should work.

the error appears if one does:
require 'matio'
because there's no global table that is registered as "matio" by this package.
Sorry for the confusion.

**Comment by lakehanne** [comment]
Oh I did not mean to say I fixed it. I meant I actually used the right command: `matio = require 'matio'` but I still got the errors.

>	
th> local matio = require 'matio'
                                                                      [0.0043s]
th> tensor = matio.load('posemat7.mat')
[string "tensor = matio.load('posemat7.mat')"]:1: attempt to index global 'matio' (a nil value)
stack traceback:
	[string "tensor = matio.load('posemat7.mat')"]:1: in main chunk
	[C]: in function 'xpcall'
	/home/lex/torch/install/share/lua/5.1/trepl/init.lua:668: in function 'repl'
	.../lex/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:199: in main chunk
	[C]: at 0x00406670	
                                                                      [0.0002s]
th> 

`posemat7.mat` is a Matlab struct.mat file saved as 

`save('posemat7.mat', 'xn', 'yn', 'zn', 'rolln', 'pitchn', 'yawn', '-v7.3');` within a matlab editor. Sorry for the trouble. Hopefully when I resolve this it will help someone. I pulled the v1.5.2 from [Sourceforge](http://sourceforge.net/projects/matio/) and all tests ran okay as in:

> ... ...           ...                       ...                      ....                                     ....
   1014: Write 2D sparse 64-bit unsigned integer array   ok
1015: Write 2D sparse 32-bit integer array            ok
1016: Write 2D sparse 32-bit unsigned integer array   ok
1017: Write 2D sparse 16-bit integer array            ok
...                       ....                                    ...                          ....        ok
1023: Write 2D sparse complex 64-bit unsigned integer complex array ok
1024: Write 2D sparse complex 32-bit integer complex array ok
1025: Write 2D sparse complex 32-bit unsigned integer complex array ok
1026: Write 2D sparse complex 16-bit integer complex array ok
1027: Write 2D sparse complex 16-bit unsigned integer complex array ok
1028: Write 2D sparse complex 8-bit integer complex array ok
1029: Write 2D sparse complex 8-bit unsigned integer complex array ok

>API Tests

>1030: Create structure array                          ok
1031: Set structure field                             ok
1032: Get structure fieldnames                        ok
1033: Add fields to structure array                   ok
1034: Linearly index a structure                      ok
1035: Index structure via dimension slices            ok
1036: Set cell array elements                         ok
1037: Linearly index cell array                       ok
1038: Index cell array via dimension slices           ok

>## ------------- ##
## Test results. ##
## ------------- ##

>All 1038 tests were successful.

**Comment by soumith** [comment]
you used:
local matio = require 'matio'

you need to use
matio = require 'matio'

local is a keyword that will only make the variable exist in the scope. In the interpreter, each line is it's own scope.

**Comment by lakehanne** [comment]
Nice. It seems to be loading the struct now. But is there a limit to the number of variables in a struct torch matio can parse?

For example, I have a struct mat file made up of 8 vectors. I can extract the first 6 vectors but the last two vectors are not 'loadable':

>Could not find variable with name: pitchn in file: posemat7.mat	
[Untitled.pdf](https://github.com/soumith/matio-ffi.torch/files/66281/Untitled.pdf)


Could not find variable with name: yawn in file: posemat7.mat

**Comment by lakehanne** [comment]
Seems that loading the last two variables individually works. 

I do not know why it can't load all of them in a single command. Thanks a lot, Soumith!
[Untitled (2).pdf](https://github.com/soumith/matio-ffi.torch/files/66283/Untitled.2.pdf)

**Comment by soumith** [comment]
Hmmm, if there's a repro that I can get, I am happy to find the bug and fix it. sorry about that.

**Comment by lakehanne** [comment]
Here's the zip file containint the matlab struct:

[posemat7.mat.zip](https://github.com/soumith/matio-ffi.torch/files/67480/posemat7.mat.zip)

Here's the code chunk that failed in lua:

```lua
     matio     = require 'matio'
    input       = matio.load('posemat7.mat', 'in')
    trans       = matio.load('posemat7.mat', 'xn', 'yn', 'zn')
    rotation   = matio.load('posemat7.mat', 'rolln', 'pitchn', yawn')
```

Trans gets loaded. Roll in `rotation ` gets loaded but not `pitchn` and `yawn`.

**Comment by ElPiloto** [comment]
Hey @soumith,  I'm having the same issue.  Is this issue closed because it was solved or because it grew stale?  If it hasn't been solved, I found a 2-line workaround that I can submit.   Let me know.

**Comment by lakehanne** [comment]
What's the 2-line workaround?

**Comment by ElPiloto** [comment]
It's here: https://github.com/ElPiloto/matio-ffi.torch/commit/7be7f932ccbe8ee906c5459e75c1e86ce2976466  

Basically, close and re-open the .MAT file between reading the matlab variables in and trying to load the actual data.

**Comment by ElPiloto** [comment]
Err, I don't know why it's pointing to a deleted branch that had a type 'vile' instead of 'file.'  I'm going to try to post the link again: https://github.com/ElPiloto/matio-ffi.torch/commit/1f424e519c2e2c70b9c078e6f285a13d95e4653f

**Comment by ElPiloto** [comment]
Hmmm, turns out that things load with that modification, but that I still get garbled up strings (which aren't garbled when I load the same .MAT file in Matlab).

**Comment by ElPiloto** [comment]
Update: it looks like loading variables individually (e.g. `str_var = matio.load('myFile.mat','str_var')` doesn't jumble the strings, but loading all of them at once without specifying names does.  @lakehanne did you end up using that workaround?

**Comment by lakehanne** [comment]
Yes, that's what I ended up doing. BTW, I got it to load  up to three variables at once. When it's more than that, it freaks out.

**Comment by ElPiloto** [comment]
@lakehanne Are there any strings in the variables when it freaks out?

**Comment by lakehanne** [comment]
No strings. All are numbers. 

I tried running [this code](https://github.com/lakehanne/FARNN/blob/master/farnn.lua) on a different linux build (Ubuntu 12.04). I have errors similar to the following:

```bash
File could not be opened: posemat7.mat	
File could not be opened: posemat7.mat	
File could not be opened: posemat7.mat	
File could not be opened: posemat7.mat	
File could not be opened: posemat7.mat	
File could not be opened: posemat7.mat	
```

Somehow, it seems the native ubuntu repo matio is not robust to all matlab versions. I saved `posemat7.mat` as a `-v7.3` which I expect should work out of the box. I will look into this again when I have the time.

**Comment by lakehanne** [comment]
Okay, I think the native libmatio in precise is compatible with matlab version 5 i.e.  `(R8) or later`. Simply saving the matlab version with the `-v6` handle works. 

```bash
save('posemat5.mat', 'xn', 'yn', 'zn', 'rolln', 'pitchn', 'yawn', 'in', '-v6');
```

I reckon the `-v7.3` version should work if the matio library is configured from source files and the switch 

```bash
--with-default-api-version=v18 --enable-mat73=yes --enable-extended-sparse=yes
```

is passed to `configure` during the build process. The matio source is available [here](http://www.hdfgroup.org/ftp/HDF5/current/src/hdf5-1.8.16.tar).
