### ISSUE TITLE
undefined symbol H5T_NATIVE_SCHAR_g

### ISSUE THREAD

**Issue by bobbens** [soumith/matio-ffi.torch#20]
Hello. I'm not familiar with Lua FFI, but I'm hitting this error (arch linux0:

/home/esimo/torch/install/share/lua/5.1/matio/ffi.lua:20: /usr/lib/libmatio.so.2: undefined symbol: H5T_NATIVE_SCHAR_g

As matio is not being linked to hdf5, if you were to compile against it you would have to link against hdf5 also. However, this is not being handled with the Lua FFI interface, and I'm not sure how to fix it, although it does seem like it should be trivial.

**Comment by soumith** [comment]
this is a general issue with your matio installation, and not with the torch bindings.
See this for example: https://github.com/BVLC/caffe/issues/668 or google for the issue.
You might have to recompile matio maybe....

**Comment by bobbens** [comment]
I see. This is default arch package. I can work around it using LD_PRELOAD=/usr/lib/libhdf5.so . Thanks,

**Comment by zaizhongche** [comment]
@bobbens  your method works for me !
