### ISSUE TITLE
No support for matlab 7.3 files

### ISSUE THREAD

**Issue by skaae** [soumith/matio-ffi.torch#3]
This is not  a huge issue, but files saved in MATLAB 7.3 format are not supported. E.g

In MATLAB

test = magic(10)
save('test7.mat','test', '-v7')
save('test73.mat','test', '-v7.3')

In torch
matio = require 'matio'
input1 = matio.load('test7.mat', 'test')
input1 = matio.load('test73.mat', 'test')  -- ERR: File could not be opened: test73.mat

**Comment by physicsman** [comment]
As far as I know, I cannot save large variables in anything other then -v7.3

**Comment by jaiabhayk** [comment]
Any solution to this ?

**Comment by soumith** [comment]
this really depends not on the bindings themselves, but on the underlying matio support.

**Comment by jaiabhayk** [comment]
Thanks for your prompt reply.
Any non-trivial work-around ?

**Comment by soumith** [comment]
https://github.com/clementfarabet/lua---mattorch maybe

**Comment by jaiabhayk** [comment]
Thanks.
